/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthNotionStartRouteImport } from './routes/auth.notion.start'
import { Route as AuthedAppDeckIdRouteImport } from './routes/_authed/app_.$deckId'
import { Route as AuthedAppDeckIdStudyRouteImport } from './routes/_authed/app_.$deckId.study'
import { Route as AuthedAppDeckIdGroupsRouteImport } from './routes/_authed/app_.$deckId.groups'
import { Route as AuthedAppDatasetIdConnectRouteImport } from './routes/_authed/app_.$datasetId.connect'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthNotionStartRoute = AuthNotionStartRouteImport.update({
  id: '/auth/notion/start',
  path: '/auth/notion/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppDeckIdRoute = AuthedAppDeckIdRouteImport.update({
  id: '/app_/$deckId',
  path: '/app/$deckId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppDeckIdStudyRoute = AuthedAppDeckIdStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthedAppDeckIdRoute,
} as any)
const AuthedAppDeckIdGroupsRoute = AuthedAppDeckIdGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedAppDeckIdRoute,
} as any)
const AuthedAppDatasetIdConnectRoute =
  AuthedAppDatasetIdConnectRouteImport.update({
    id: '/app_/$datasetId/connect',
    path: '/app/$datasetId/connect',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthedAppRoute
  '/app/$deckId': typeof AuthedAppDeckIdRouteWithChildren
  '/auth/notion/start': typeof AuthNotionStartRoute
  '/app/$datasetId/connect': typeof AuthedAppDatasetIdConnectRoute
  '/app/$deckId/groups': typeof AuthedAppDeckIdGroupsRoute
  '/app/$deckId/study': typeof AuthedAppDeckIdStudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthedAppRoute
  '/app/$deckId': typeof AuthedAppDeckIdRouteWithChildren
  '/auth/notion/start': typeof AuthNotionStartRoute
  '/app/$datasetId/connect': typeof AuthedAppDatasetIdConnectRoute
  '/app/$deckId/groups': typeof AuthedAppDeckIdGroupsRoute
  '/app/$deckId/study': typeof AuthedAppDeckIdStudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/app_/$deckId': typeof AuthedAppDeckIdRouteWithChildren
  '/auth/notion/start': typeof AuthNotionStartRoute
  '/_authed/app_/$datasetId/connect': typeof AuthedAppDatasetIdConnectRoute
  '/_authed/app_/$deckId/groups': typeof AuthedAppDeckIdGroupsRoute
  '/_authed/app_/$deckId/study': typeof AuthedAppDeckIdStudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/app/$deckId'
    | '/auth/notion/start'
    | '/app/$datasetId/connect'
    | '/app/$deckId/groups'
    | '/app/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/app/$deckId'
    | '/auth/notion/start'
    | '/app/$datasetId/connect'
    | '/app/$deckId/groups'
    | '/app/$deckId/study'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/privacy'
    | '/terms'
    | '/_authed/app'
    | '/_authed/app_/$deckId'
    | '/auth/notion/start'
    | '/_authed/app_/$datasetId/connect'
    | '/_authed/app_/$deckId/groups'
    | '/_authed/app_/$deckId/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthNotionStartRoute: typeof AuthNotionStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/notion/start': {
      id: '/auth/notion/start'
      path: '/auth/notion/start'
      fullPath: '/auth/notion/start'
      preLoaderRoute: typeof AuthNotionStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app_/$deckId': {
      id: '/_authed/app_/$deckId'
      path: '/app/$deckId'
      fullPath: '/app/$deckId'
      preLoaderRoute: typeof AuthedAppDeckIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app_/$deckId/study': {
      id: '/_authed/app_/$deckId/study'
      path: '/study'
      fullPath: '/app/$deckId/study'
      preLoaderRoute: typeof AuthedAppDeckIdStudyRouteImport
      parentRoute: typeof AuthedAppDeckIdRoute
    }
    '/_authed/app_/$deckId/groups': {
      id: '/_authed/app_/$deckId/groups'
      path: '/groups'
      fullPath: '/app/$deckId/groups'
      preLoaderRoute: typeof AuthedAppDeckIdGroupsRouteImport
      parentRoute: typeof AuthedAppDeckIdRoute
    }
    '/_authed/app_/$datasetId/connect': {
      id: '/_authed/app_/$datasetId/connect'
      path: '/app/$datasetId/connect'
      fullPath: '/app/$datasetId/connect'
      preLoaderRoute: typeof AuthedAppDatasetIdConnectRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedAppDeckIdRouteChildren {
  AuthedAppDeckIdGroupsRoute: typeof AuthedAppDeckIdGroupsRoute
  AuthedAppDeckIdStudyRoute: typeof AuthedAppDeckIdStudyRoute
}

const AuthedAppDeckIdRouteChildren: AuthedAppDeckIdRouteChildren = {
  AuthedAppDeckIdGroupsRoute: AuthedAppDeckIdGroupsRoute,
  AuthedAppDeckIdStudyRoute: AuthedAppDeckIdStudyRoute,
}

const AuthedAppDeckIdRouteWithChildren = AuthedAppDeckIdRoute._addFileChildren(
  AuthedAppDeckIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedAppDeckIdRoute: typeof AuthedAppDeckIdRouteWithChildren
  AuthedAppDatasetIdConnectRoute: typeof AuthedAppDatasetIdConnectRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedAppDeckIdRoute: AuthedAppDeckIdRouteWithChildren,
  AuthedAppDatasetIdConnectRoute: AuthedAppDatasetIdConnectRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthNotionStartRoute: AuthNotionStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
